AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  lending:
    Type: AWS::Serverless::Function
    Properties:
      Handler: turing_oracle.lambda_handler
      Runtime: python3.9
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/quote'
            Method: get
